disabled_rules:
  - trailing_comma
  - force_cast
  - type_body_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - discouraged_optional_boolean
  - empty_string
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Package.swift

line_length:
  warning: 140
  error: 200

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - to
    - db
    - os
    - op

nesting:
  type_level: 3
  function_level: 3

reporter: "xcode"
